name: Feature Request
description: Request a feature
title: "[FEAT]: "
labels:
  - "Feature"
  - "Pending Review"
  - "Enhancements"
# projects:
# assignees:

body:
- type: checkboxes
  id: prerequisites
  attributes:
    label: Prerequisites
    description: Please answer the following questions.
    options:
      - label: I have searched for [existing issues](https://github.com/ArkhamCookie/deno-wordnik/issues) that already report this problem, without success.
        required: true
      - label: I would be willing to help implement this feature.
        required: false

- type: textarea
  attributes:
    label: Describe the Feature Request
    description: A clear and concise description of what the feature does.
  validations:
    required: true

- type: textarea
  attributes:
    label: Is this feature realted to a problem?
- type: textarea
  attributes:
    label: Describe the Use Case
    description: A clear and concise use case for this feature.

- type: textarea
  attributes:
    label: Anything else?
    description: List any other information that is relevant to your issue. Stack traces, related issues, suggestions on how to implement, Stack Overflow links, forum links, etc.
